### ISSUE TITLE
Notifier not working on Logger extends Log4J

### ISSUE THREAD

**Issue by kevffn** [airbrake/airbrake-java#27]
Hi,

I have used air-brake for Java with a customized logger which basically is an extension of Log4J. But error notification did not work.  air-brake server was not getting the error and no email notification was sent out. 

The logger I used is from Wowza Media Server

I copy the error log and log4j setting below, hope this will help.
# 
# Error Log
# Date: 2014-04-17
# Fields: x-severity     x-category      x-event date    time    c-client-id     c-ip    c-port  cs-bytes        sc-bytes        x-duration      x-sname x-stream-id     x-spos  sc-stream-bytes cs-stream-bytes x-file-size     x-file-length   x-ctx   x-comment

ERROR   server  comment 2014-04-17      13:43:41        -       -       -       -       -       17.514  -       -       -       -       -       -       -       -       startPublisher(): java.lang.NullPointerException
ERROR   server  comment 2014-04-17      13:43:41        -       -       -       -       -       17.515  -       -       -       -       -       -       -       -       startPublisher(): java.lang.NullPointerException
        at com.xyz.broadcast.AMFWowza.onCall(AMFWowzaBroadcast.java:332)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.wowza.wms.module.ModuleFunction.invoke(Unknown Source)
        at com.wowza.wms.module.ModuleFunctions.a(Unknown Source)
        at com.wowza.wms.module.ModuleFunctions.onCall(Unknown Source)
        at com.wowza.wms.request.RequestProcessFunctions.processFunctions(Unknown Source)
        at com.wowza.wms.request.RequestProcessData.flushFunction(Unknown Source)
        at com.wowza.wms.request.RequestProcessData.processNextRequest(Unknown Source)
        at com.wowza.wms.client.ClientWorker.processNextReq(Unknown Source)
        at com.wowza.wms.request.RTMPRequestAdapter.service(Unknown Source)
        at com.wowza.wms.server.ServerHandler.a(Unknown Source)
        at com.wowza.wms.server.ServerHandler.a(Unknown Source)
        at com.wowza.wms.server.ServerHandler.messageReceived(Unknown Source)
        at com.wowza.wms.server.ServerHandlerThreadedSession.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
# 
# Log4J properties

log4j.rootCategory=INFO, stdout, airbrake, serverAccess, serverError
# log4j.rootLogger=INFO, stdout, airbrake, serverAccess, serverError
# Console appender

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.File=/log/wowza/air_stdout.log
log4j.appender.stdout.layout=com.wowza.wms.logging.ECLFPatternLayout
log4j.appender.stdout.layout.Fields=x-severity,x-category,x-event,x-ctx,x-comment
log4j.appender.stdout.layout.OutputHeader=true
log4j.appender.stdout.layout.QuoteFields=false
log4j.appender.stdout.layout.Delimeter=space
# Airbrake appender

log4j.appender.airbrake=airbrake.AirbrakeAppender
log4j.appender.airbrake.api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
log4j.appender.airbrake.env=production
log4j.appender.airbrake.enabled=true
log4j.appender.airbrake.url=http://api.airbrake.io/notifier_api/v2/notices
# Access appender

log4j.appender.serverAccess=org.apache.log4j.DailyRollingFileAppender
log4j.appender.serverAccess.DatePattern='.'yyyy-MM-dd
log4j.appender.serverAccess.File=/log/wowza/air_access.log
log4j.appender.serverAccess.layout=com.wowza.wms.logging.ECLFPatternLayout
log4j.appender.serverAccess.layout.Fields=date,time,tz,x-event,x-category,x-severity,x-status,x-ctx,x-comment,x-vhost,x-app,x-appinst,x-duration,s-ip,s-port,s-uri,c-ip,c-proto,c-referrer,c-user-agent,c-client-id,cs-bytes,sc-bytes,x-stream-id,x-spos,cs-stream-bytes,sc-stream-bytes,x-sname,x-sname-query,x-file-name,x-file-ext,x-file-size,x-file-length,x-suri,x-suri-stem,x-suri-query,cs-uri-stem,cs-uri-query
log4j.appender.serverAccess.layout.OutputHeader=true
log4j.appender.serverAccess.layout.QuoteFields=false
log4j.appender.serverAccess.layout.Delimeter=tab
# Error appender

log4j.appender.serverError=org.apache.log4j.DailyRollingFileAppender
log4j.appender.serverError.DatePattern='.'yyyy-MM-dd
log4j.appender.serverError.File=/log/wowza/air_error.log
log4j.appender.serverError.layout=com.wowza.wms.logging.ECLFPatternLayout
log4j.appender.serverError.layout.Fields=x-severity,x-category,x-event;date,time,c-client-id,c-ip,c-port,cs-bytes,sc-bytes,x-duration,x-sname,x-stream-id,x-spos,sc-stream-bytes,cs-stream-bytes,x-file-size,x-file-length,x-ctx,x-comment
log4j.appender.serverError.layout.OutputHeader=true
log4j.appender.serverError.layout.QuoteFields=false
log4j.appender.serverError.layout.Delimeter=tab
log4j.appender.serverError.Threshold=WARN

Thanks

Kev

**Comment by elliotmoso** [comment]
Any news on this?

**Comment by vmihailenco** [comment]
Closing as stale.
