### ISSUE TITLE
Backtrace for java exceptions.

### ISSUE THREAD

**Issue by igortwago** [airbrake/airbrake-java#51]
I am a java developer, and I am using airbrake in a java project. 
I don't understand why, but airbrake transforms java stack frames into the format, which is not very useful for java developers. 
For example I have stack frames 
```java
["java.lang.RuntimeException"," 	at TestException.method(TestException.java:19)"," 	at TestException.main(TestException.java:25)]"
```
In a console or a log file it would look like 
```java
Exception in thread "main" java.lang.RuntimeException
	at TestException.method(TestException.java:19)
	at TestException.main(TestException.java:25)
```
When I have an exception like this one, I can copy it to a java IDE stack trace console and access any code line from this stack trace. 

But in airbrake backtrace looks like 
```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```
Java IDEs don't support this format. 

I am using java notifier 

```xml
		<dependency>
			<groupId>io.airbrake</groupId>
			<artifactId>airbrake-java</artifactId>
			<version>2.2.8</version>
		</dependency>

```

```java
		try {
			method();
		}
		catch(Throwable t) {
		    
			Map<String, Object> errorMessages = new HashMap<>();
			
			
	        AirbrakeNotice notice = new AirbrakeNotice("key",
	                "twago-dev", "dev",
	                "errorMessage", "errorClass", new Backtrace(
	                        Lists.newArrayList("java.lang.RuntimeException"," 	at TestException.method(TestException.java:19)"," 	at TestException.main(TestException.java:25)")),
	                Collections.<String, Object> emptyMap(),
	                Collections.<String, Object> emptyMap(), errorMessages,
	                Collections.<String> emptyList(), true, "errorUrl", "component");

	        
		    AirbrakeNotifier notifier = new AirbrakeNotifier("http://api.airbrake.io/notifier_api/v2/notices");
		    notifier.notify(notice);
		    
		}		
	}
```
The idea is when I send backtrace with this values 
```java
java.lang.RuntimeException
 	at TestException.method(TestException.java:19)
 	at TestException.main(TestException.java:25)
```
airbrake shows backtrace in this way 
```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```

I have found a place where this transformation is implemented 
```java
	public BacktraceLine(String line) {
		String classAndMethodName = line.replaceAll("\\(.*", "").replaceAll("^at ", "");

		int periodSepIndex = classAndMethodName.lastIndexOf(".");
		if (periodSepIndex > 0) {
			className = classAndMethodName.substring(0, classAndMethodName.lastIndexOf("."));
		} else {
			className = classAndMethodName;
		}
		fileName = fileName(line);
		lineNumber = lineNumber(line);
		methodName = methodName(classAndMethodName);
	}

```
```

**Comment by zefer** [comment]
Hi @igortwago. Thanks for getting in touch.

Are you referring to how we display the backtrace on the Airbrake web UI?

The 2 examples you gave are identical, was that a mistake?

> But in airbrake backtrace looks like 
```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```

> The idea is when I send backtrace with this values 
> airbrake shows backtrace in this way 
```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```

**Comment by igortwago** [comment]
I send this information
```java
java.lang.RuntimeException
 	at TestException.method(TestException.java:19)
 	at TestException.main(TestException.java:25)
```
but airbrake shows backtrace in this way 

```java
java.lang.RuntimeException:-1 in java.lang.RuntimeException
TestException.java:19 in 	at TestException.method
TestException.java:25 in 	at TestException.main
```

**Comment by vmihailenco** [comment]
I've moved this to https://github.com/airbrake/javabrake/issues/7, but it is complicated because it requires support in UI and backend simply does not have all info required to reconstruct classing Java backtrace.
